Начинаем программировать
htmlacademy-react/235995-six-cities-14 pull request #2
Opened 2023-10-11 10:59 UTC by sasstr

---
:mortar_board: [Начинаем программировать](https://up.htmlacademy.ru/react/14/user/235995/tasks/4)

2023-10-11 14:47 UTC, baileys-li requested changes

2023-10-11 14:47 UTC, baileys-li commented on src/components/card/card.tsx
> +function Card(): JSX.Element {
Лучше сразу сделать так, чтобы карточка принимала проппсы

2023-10-11 15:49 UTC, sasstr commented on src/components/card/card.tsx
> +function Card(): JSX.Element {
Просто подумал все равно потом через редакс все будет приезжать и не стал делать пропс-дрилинг. А откуда кидать? С самого верху? Или на один уровень выше?

2023-10-11 17:17 UTC, sasstr commented on src/components/card/card.tsx
> +function Card(): JSX.Element {
Не придумал как быть с типами. Нужен совет как быть.

2023-10-11 18:22 UTC, baileys-li commented on src/components/card/card.tsx
> +function Card(): JSX.Element {
Отложим до субботы? Тогда полайвкодю

2023-10-11 19:55 UTC, sasstr commented on src/components/card/card.tsx
> +function Card(): JSX.Element {
До субботы я бы еще роутинг бы успел сделать... Но в субботу в любом случае с удовольствием посмотрю лучшие практики.

2023-10-12 17:00 UTC, baileys-li commented
В сб дополнительно разберём

2023-10-12 17:06 UTC, merged